var CONFIG = {
    "august_2024": {
        files: [
            {
                electionEvent: 'Primaries', 
                fileName: 'Florida_primary.json', 
                entry: 'ElectionPlaylist', 
                title: '2024 August Primary'
            }, 
            {
                electionEvent: 'Local',
                fileName: 'Florida_local.json', 
                entry: 'ElectionEvent', 
                title: '2024 August Primary'
            }
        ]
    }, 
    "november_2024": {
        files: [
            {
                electionEvent: 'State Races',
                fileName: 'state_races.json', 
                entry: 'ElectionEvent', 
                title: 'Presidential Election 2024', 
                hide: ["Florida District 1",
                        "Florida District 2",
                        "Florida District 3",
                        "Florida District 4",
                        "Florida District 5",
                        "Florida District 6",
                        "Florida District 7",
                        "Florida District 8",
                        "Florida District 9",
                        "Florida District 10",
                        "Florida District 11",
                        "Florida District 12",
                        "Florida District 13",
                        "Florida District 14",
                        "Florida District 15",
                        "Florida District 16",
                        "Florida District 20",
                        "Florida District 21",
                        "Florida District 22",
                        "Florida District 23",
                        "Florida District 24",
                        "Florida District 25",
                        "Florida District 28",
                        "Florida District 30",
                        "Florida District 31",
                        "Florida District 32",
                        "Florida District 34",
                        "Florida District 35",
                        "Florida District 36",
                        "Florida District 37",
                        "Florida District 38",
                        "Florida District 39",
                        "Florida District 40",
                        "Florida District 41",
                        "Florida District 42",
                        "Florida District 43",
                        "Florida District 44",
                        "Florida District 45",
                        "Florida District 46",
                        "Florida District 47",
                        "Florida District 48",
                        "Florida District 49",
                        "Florida District 50",
                        "Florida District 51",
                        "Florida District 52",
                        "Florida District 53",
                        "Florida District 54",
                        "Florida District 55",
                        "Florida District 56",
                        "Florida District 57",
                        "Florida District 58",
                        "Florida District 59",
                        "Florida District 60",
                        "Florida District 61",
                        "Florida District 62",
                        "Florida District 63",
                        "Florida District 64",
                        "Florida District 65",
                        "Florida District 66",
                        "Florida District 67",
                        "Florida District 68",
                        "Florida District 69",
                        "Florida District 70",
                        "Florida District 71",
                        "Florida District 72",
                        "Florida District 73",
                        "Florida District 74",
                        "Florida District 84",
                        "Florida District 85",
                        "Florida District 86",
                        "Florida District 87",
                        "Florida District 88",
                        "Florida District 89",
                        "Florida District 90",
                        "Florida District 91",
                        "Florida District 92",
                        "Florida District 93",
                        "Florida District 94",
                        "Florida District 95",
                        "Florida District 96",
                        "Florida District 97",
                        "Florida District 98",
                        "Florida District 99",
                        "Florida District 100",
                        "Florida District 101",
                        "Florida District 102",
                        "Florida District 103",
                        "Florida District 104",
                        "Florida District 105",
                        "Florida District 106",
                        "Florida District 107",
                        "Florida District 108",
                        "Florida District 109",
                        "Florida District 110",
                        "Florida District 111",
                        "Florida District 112",
                        "Florida District 113",
                        "Florida District 114",
                        "Florida District 115",
                        "Florida District 116",
                        "Florida District 117",
                        "Florida District 118",
                        "Florida District 119",
                        "Florida District 120",]
            }, 
            {
                electionEvent: 'County Races',
                fileName: 'county_races.json', 
                entry: 'ElectionEvent', 
                title: 'Presidential Election 2024'
            }, 
            {
                electionEvent: 'Presidential Results',
                fileName: 'presidential_results.json', 
                entry: 'ElectionEvent', 
                title: 'Presidential Election 2024'
            }
        ]
    }
}